version: '3.8'

services:
  # FlowState App
  flowstate:
    image: gulenda/flowstate:latest
    restart: always
    deploy:
      labels:
        - "traefik.enable=true"
        # HTTP -> HTTPS redirect
        - "traefik.http.routers.flowstate-http.rule=Host(`tasks.loopmind.cloud`)"
        - "traefik.http.routers.flowstate-http.entrypoints=web"
        - "traefik.http.routers.flowstate-http.middlewares=redirect-to-https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        # HTTPS
        - "traefik.http.routers.flowstate.rule=Host(`tasks.loopmind.cloud`)"
        - "traefik.http.routers.flowstate.entrypoints=websecure"
        - "traefik.http.routers.flowstate.tls=true"
        - "traefik.http.routers.flowstate.tls.certresolver=letsencrypt"
        - "traefik.http.services.flowstate.loadbalancer.server.port=80"
      placement:
        constraints:
          - node.role == manager
    networks:
      - traefik-public
    environment:
      - NODE_ENV=production

networks:
  traefik-public:
    external: true
