version: '3.8'

services:
  app:
    image: guilhermerodrigues10/flowstate:latest
    container_name: flowstate-app
    restart: always
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flowstate.rule=Host(`tasks.loopmind.cloud`)"
      - "traefik.http.routers.flowstate.entrypoints=websecure"
      - "traefik.http.routers.flowstate.tls.certresolver=letsencrypt"
      - "traefik.http.services.flowstate.loadbalancer.server.port=80"
      # Redirect HTTP to HTTPS
      - "traefik.http.routers.flowstate-http.rule=Host(`tasks.loopmind.cloud`)"
      - "traefik.http.routers.flowstate-http.entrypoints=web"
      - "traefik.http.routers.flowstate-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    environment:
      - NODE_ENV=production

networks:
  traefik-public:
    external: true
